index:
  path: /MailJet/API/campaignoverview/
  controller: 'WebEtDesignMailingBundle:MailJet\MailJet:getCampaign'

unsub:
  path: /mailing/unsub
  controller: 'WebEtDesignMailingBundle:MailJet\MailJet:unsub'
