services:
    mailing.admin.mailJet:
        class: WebEtDesign\MailingBundle\Block\MailJet\Base
        arguments:
          - ~
          - '@templating'

        tags:
          - { name: sonata.block }


    WebEtDesign\MailingBundle\EventListener\UpdateEmailing:
      tags:
        - { name: doctrine.event_subscriber, connection: default }
