services:
    WebEtDesign\MailingBundle\Controller\MailJet\MailJetController:
      autowire: true # or define your controller constructor and configure its arguments explicitly
      tags: ['controller.service_arguments']

    mailing.admin.mailJet:
        class: WebEtDesign\MailingBundle\Block\MailJet\Base
        arguments:
          - ~
          - '@templating'
          - '@doctrine.orm.entity_manager'
          - '%wd_mailing.mailjet.public_key%'
          - '%wd_mailing.mailjet.secret_key%'

        tags:
          - { name: sonata.block }


  # ===============================================
  # LISTENER
  # ===============================================

    mailing.Emailing.listner:
      class: WebEtDesign\MailingBundle\EventListener\UpdateEmailing
      public: true
      tags:
        - { name: doctrine.event_subscriber, connection: default }

    mailing.User.listner:
      class: WebEtDesign\MailingBundle\EventListener\UpdateUser
      public: true
      tags:
        - { name: doctrine.event_subscriber, connection: default }

  # ===============================================
  # REPOSITORY
  # ===============================================

    WebEtDesign\MailingBundle\Repository\:
      resource: '../../Repository'
      autowire: true
      tags: ['doctrine.repository_service']

  # ===============================================
  # ADMIN
  # ===============================================


    mailing.emailing.admin:
      class: WebEtDesign\MailingBundle\Admin\MailingEmailingAdmin
      arguments: [~, WebEtDesign\MailingBundle\Entity\MailingEmailing, WebEtDesign\MailingBundle\Controller\MailJet\MailingEmailingAdminController]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Mailing, label: MailJet, icon: <i class="fa fa-envelope"></i> }
      public: true
