WebEtDesign\MailingBundle\Entity\Emailing:
    type: entity
    table: mailing__emailing
    repositoryClass: WebEtDesign\MailingBundle\Repository\MailingEmailingRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY

    lifecycleCallbacks: {  }
